import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          GlassEffectLoginPageBlue(),
        ]),
      ),
    );
  }
}

class GlassEffectLoginPageBlue extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1920,
          height: 1080,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: RadialGradient(
              center: Alignment(0.99, 0.74),
              radius: 0.98,
              colors: [Color(0xFF0084FF), Color(0xFF003464)],
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 1881,
                height: 1036,
                decoration: BoxDecoration(
                  image: DecorationImage(
                    image: NetworkImage("https://via.placeholder.com/1881x1036"),
                    fit: BoxFit.fill,
                  ),
                ),
              ),
              Container(
                width: 792,
                height: 896,
                decoration: ShapeDecoration(
                  color: Color(0x475782C1),
                  shape: RoundedRectangleBorder(
                    side: BorderSide(width: 3, color: Color(0xFF5882C1)),
                    borderRadius: BorderRadius.circular(40),
                  ),
                ),
              ),
              Container(
                width: 153,
                height: 167,
                decoration: BoxDecoration(
                  image: DecorationImage(
                    image: NetworkImage("https://via.placeholder.com/153x167"),
                    fit: BoxFit.fill,
                  ),
                ),
              ),
              Container(
                width: 577.55,
                height: 486.96,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0.19,
                      top: 0,
                      child: SizedBox(
                        width: 241.04,
                        height: 55.84,
                        child: Text(
                          'Create an Account',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 38,
                            fontFamily: 'Allan',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 3.63,
                      top: 422.03,
                      child: Container(
                        width: 573.91,
                        height: 64.93,
                        decoration: ShapeDecoration(
                          color: Color(0xFF003465),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 253.86,
                      top: 440.21,
                      child: SizedBox(
                        width: 84.94,
                        height: 29.87,
                        child: Text(
                          'Sign up',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Aclonica',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 90.90,
                      child: Container(
                        width: 574.10,
                        height: 236.34,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0.19,
                              top: 33.76,
                              child: Container(
                                width: 573.91,
                                height: 64.93,
                                decoration: ShapeDecoration(
                                  color: Colors.white,
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(width: 1, color: Color(0xFFBCBEC0)),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0.19,
                              top: 0,
                              child: SizedBox(
                                width: 120.52,
                                height: 25.97,
                                child: Text(
                                  'ID Number',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 18,
                                    fontFamily: 'Aclonica',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0.19,
                              top: 171.41,
                              child: Container(
                                width: 573.91,
                                height: 64.93,
                                decoration: ShapeDecoration(
                                  color: Colors.white,
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(width: 1, color: Color(0xFFBCBEC0)),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 137.63,
                              child: SizedBox(
                                width: 135,
                                height: 27,
                                child: Text(
                                  'Password',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 18,
                                    fontFamily: 'Aclonica',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 26.59,
                              top: 55.84,
                              child: SizedBox(
                                width: 115.93,
                                height: 22.08,
                                child: Text(
                                  '****************',
                                  style: TextStyle(
                                    color: Color(0xFFBCBEC0),
                                    fontSize: 14,
                                    fontFamily: 'ABeeZee',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 26.59,
                              top: 193.48,
                              child: SizedBox(
                                width: 115.93,
                                height: 22.08,
                                child: Text(
                                  '****************',
                                  style: TextStyle(
                                    color: Color(0xFFBCBEC0),
                                    fontSize: 14,
                                    fontFamily: 'ABeeZee',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 26.59,
                              top: 55.84,
                              child: SizedBox(
                                width: 115.93,
                                height: 22.08,
                                child: Text(
                                  '****************',
                                  style: TextStyle(
                                    color: Color(0xFFBCBEC0),
                                    fontSize: 14,
                                    fontFamily: 'ABeeZee',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 531.63,
                              top: 193.48,
                              child: Container(
                                width: 18.37,
                                height: 20.78,
                                clipBehavior: Clip.antiAlias,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(40),
                                  ),
                                ),
                                child: Stack(children: [
                                ,
                                ]),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}